# Generated by Django 3.2.14 on 2022-07-19 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('task_is_done', models.BooleanField(default=True)),
                ('task_created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_updated_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
